version: '3'
services:
  proxy:
    container_name: proxy
    build: ./.docker/proxy
    ports:
      - 3012:80
    volumes: 
      - ./proxy:/proxy
    depends_on:
      - aob
      - vue

  aob:
    container_name: aob
    image: mathcovax/anotherback:2.3.4
    environment:
      AOB_V: "2.10.13"
    volumes: 
      - ./aob:/api
    env_file:
      - ./aob/.env
    depends_on:
      - postgres
    # expose:
    #   - 5555
    # ports:
    #   - 5555:5555

  installer-vue:
    container_name: installer-vue
    image: node:18.13.0-alpine
    volumes:
      - ./vue:/home/node/vue
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/vue
    entrypoint: npm i

  builder-vue:
    container_name: builder-vue
    image: node:18.13.0-alpine
    volumes:
      - ./vue:/home/node/vue
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/vue
    entrypoint: npm run build
    depends_on:
      installer-vue: 
        condition: service_completed_successfully

  vue:
    container_name: vue
    image: node:18.13.0-alpine
    volumes:
      - ./vue:/home/node/vue
    working_dir: /home/node/vue
    command: npm run preview
    ports:
      - 3333:80
    depends_on:
      builder-vue: 
        condition: service_completed_successfully

  postgres:
    container_name: postgres
    image: postgres:15.2
    env_file: ./aob/.env
    volumes:
    - postgres-data-prod:/var/lib/postgresql/data

volumes:
  postgres-data-prod:
