version: '3'
services:
  proxy:
    container_name: proxy
    build: ./.docker/proxy
    ports:
      - 1506:80
    volumes: 
      - ./proxy:/proxy

  aob:
    container_name: aob
    image: mathcovax/anotherback:2.3.4
    expose:
      - 5555
    environment:
      AOB_V: "2.13.17"
    ports:
      - 5555:5555
    volumes: 
      - ./aob:/api
    depends_on:
      - postgres

  installer-duplo:
    container_name: installer-duplo
    image: node:20.3.1-alpine
    user: node
    volumes:
      - ./duplo:/home/node/duplo
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/duplo
    entrypoint: npm i

  duplo:
    container_name: duplo
    image: node:20.3.1-alpine
    volumes:
      - ./duplo:/home/node/duplo
    working_dir: /home/node/duplo
    command: npm run dev
    depends_on:
      installer-duplo: 
        condition: service_completed_successfully
  
  installer-vue:
    container_name: installer-vue
    image: node:18.13.0-alpine
    user: node
    volumes:
      - ./vue:/home/node/vue
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/vue
    entrypoint: npm i

  vue:
    container_name: vue
    image: node:18.13.0-alpine
    volumes:
      - ./vue:/home/node/vue
    working_dir: /home/node/vue
    command: npm run dev
    depends_on:
      installer-vue: 
        condition: service_completed_successfully

  postgres:
    container_name: postgres
    image: postgres:15.2
    env_file: ./aob/.env
    volumes:
    - postgres-data:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432

volumes:
  postgres-data:
