#! /usr/bin/sh

DOCKER_COMPOSE="docker compose"

EXEC_AOB="$DOCKER_COMPOSE exec -u node -w /api aob"
EXEC_DUPLO="$DOCKER_COMPOSE exec -u node -w /home/node/duplo duplo"

POSTGRES_CONTAINER_SERVICE="postgres"
EXEC_POSTGRES="$DOCKER_COMPOSE exec $POSTGRES_CONTAINER_SERVICE"

if [ "$1" == "up" ]
then
	$DOCKER_COMPOSE up $2

elif [ "$1" == "down" ]
then
	$DOCKER_COMPOSE down $2
	
elif [ "$1" == "bash" ]
then
	$EXEC_AOB /bin/bash

elif [ "$1" == "studio" ]
then
	$EXEC_AOB npx prisma studio

elif [ "$1" == "migrate" ]
then
	$EXEC_AOB npx prisma migrate dev
	$EXEC_AOB npx prisma generate
	$EXEC_DUPLO npx prisma generate

elif [ "$1" == "generate" ]
then
	$EXEC_AOB npx prisma generate
	$EXEC_DUPLO npx prisma generate

elif [ "$1" == "deploy" ]
then
	$EXEC_AOB npx prisma migrate deploy

elif [ "$1" == "push" ]
then
	$EXEC_AOB npx prisma db push
	
elif [ "$1" == "data_fix" ]
then
	$EXEC_AOB npx prisma migrate reset --force
	$EXEC_AOB node src/prisma/dataFixtures.js
elif [ "$1" == "save_db" ]
then
	$EXEC_POSTGRES pg_dumpall -c -U mathcovax > ./save_db/dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
else
	echo "error arg"
fi